language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-spl-jquery' ]; then cd .. && eval "mv $currentfolder generator-spl-jquery" && cd generator-spl-jquery; fi